name: Automation Nightly Reset

on:
  schedule:
    # schedule build every night
    - cron: "0 19 * * *"
  workflow_dispatch:

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/trigger-build-caprover.yml
    secrets: inherit
    with:
      upload-artifact: true
