name: Trigger build of all BO Services

on:
  workflow_call:
    inputs:
      upload-artifact:
        type: boolean
        default: true

jobs:
  restart-bo-dolah:
    name: restart-bo-dolah
    runs-on: "ubuntu-20.04"
    steps:
      - name: Restart BO_CRYPTO_API
        run: |
          echo "BO_CRYPTO_API"
      - name: cURL AxiosJS
        # You may pin to the exact commit or the version.
        # uses: indiesdev/curl@5f733a4ab67799ec174b9b9b3f8d78100ae084e8
        uses: indiesdev/curl@v1.1
        with:
          # The target url
          url: ${{ secrets.BO_CRYPTO_API }}
          # The request method, basically one of GET, POST, PUT, PATCH
          method: "POST" # optional, default is GET
          # List of status codes to be accepted, else it is considerred to be failed
      - name: Restart BoDolah
        run: |
          echo "BoDolah"
      - name: cURL AxiosJS
        # You may pin to the exact commit or the version.
        # uses: indiesdev/curl@5f733a4ab67799ec174b9b9b3f8d78100ae084e8
        uses: indiesdev/curl@v1.1
        with:
          # The target url
          url: ${{ secrets.BODOLAH }}
          # The request method, basically one of GET, POST, PUT, PATCH
          method: "POST" # optional, default is GET
          # List of status codes to be accepted, else it is considerred to be failed
      - name: Restart BO_FLOW
        run: |
          echo "BO_FLOW"
      - name: cURL AxiosJS
        # You may pin to the exact commit or the version.
        # uses: indiesdev/curl@5f733a4ab67799ec174b9b9b3f8d78100ae084e8
        uses: indiesdev/curl@v1.1
        with:
          # The target url
          url: ${{ secrets.BO_FLOW }}
          # The request method, basically one of GET, POST, PUT, PATCH
          method: "POST" # optional, default is GET
          # List of status codes to be accepted, else it is considerred to be failed
      - name: Restart BO_ARBITRUM
        run: |
          echo "BO_ARBITRUM"
      - name: cURL AxiosJS
        # You may pin to the exact commit or the version.
        # uses: indiesdev/curl@5f733a4ab67799ec174b9b9b3f8d78100ae084e8
        uses: indiesdev/curl@v1.1
        with:
          # The target url
          url: ${{ secrets.BO_ARBITRUM }}
          # The request method, basically one of GET, POST, PUT, PATCH
          method: "POST" # optional, default is GET
          # List of status codes to be accepted, else it is considerred to be failed
      - name: Restart BO_NASDAQ
        run: |
          echo "BO_NASDAQ"
      - name: cURL AxiosJS
        # You may pin to the exact commit or the version.
        # uses: indiesdev/curl@5f733a4ab67799ec174b9b9b3f8d78100ae084e8
        uses: indiesdev/curl@v1.1
        with:
          # The target url
          url: ${{ secrets.BO_NASDAQ }}
          # The request method, basically one of GET, POST, PUT, PATCH
          method: "POST" # optional, default is GET
          # List of status codes to be accepted, else it is considerred to be failed
          
      - name: Restart SuperTrade OPT
        run: |
          echo "Super Trade OPT"
      - name: cURL AxiosJS
        # You may pin to the exact commit or the version.
        # uses: indiesdev/curl@5f733a4ab67799ec174b9b9b3f8d78100ae084e8
        uses: indiesdev/curl@v1.1
        with:
          # The target url
          url: ${{ secrets.BOSUPERTRADEOPT }}
          # The request method, basically one of GET, POST, PUT, PATCH
          method: "POST" # optional, default is GET
          # List of status codes to be accepted, else it is considerred to be failed
      - name: Restart FastTrade
        run: |
          echo "FastTrade"
      - name: cURL AxiosJS
        # You may pin to the exact commit or the version.
        # uses: indiesdev/curl@5f733a4ab67799ec174b9b9b3f8d78100ae084e8
        uses: indiesdev/curl@v1.1
        with:
          # The target url
          url: ${{ secrets.BOFASTTRADE }}
          # The request method, basically one of GET, POST, PUT, PATCH
          method: "POST" # optional, default is GET
          # List of status codes to be accepted, else it is considerred to be failed
      - name: Restart SmartTradeX
        run: |
          echo "SmartTradeX"
      - name: cURL AxiosJS
        # You may pin to the exact commit or the version.
        # uses: indiesdev/curl@5f733a4ab67799ec174b9b9b3f8d78100ae084e8
        uses: indiesdev/curl@v1.1
        with:
          # The target url
          url: ${{ secrets.BOSMARTTRADEX }}
          # The request method, basically one of GET, POST, PUT, PATCH
          method: "POST" # optional, default is GET
          # List of status codes to be accepted, else it is considerred to be failed
      - name: Restart FTMXTrade
        run: |
          echo "FTMXTrade"
      - name: cURL AxiosJS
        # You may pin to the exact commit or the version.
        # uses: indiesdev/curl@5f733a4ab67799ec174b9b9b3f8d78100ae084e8
        uses: indiesdev/curl@v1.1
        with:
          # The target url
          url: ${{ secrets.BOFTMXTRADE }}
          # The request method, basically one of GET, POST, PUT, PATCH
          method: "POST" # optional, default is GET
          # List of status codes to be accepted, else it is considerred to be failed
      - name: Restart DreamChance
        run: |
          echo "DreamChance"
      - name: cURL AxiosJS
        # You may pin to the exact commit or the version.
        # uses: indiesdev/curl@5f733a4ab67799ec174b9b9b3f8d78100ae084e8
        uses: indiesdev/curl@v1.1
        with:
          # The target url
          url: ${{ secrets.BODREAMCHANCE }}
          # The request method, basically one of GET, POST, PUT, PATCH
          method: "POST" # optional, default is GET
          # List of status codes to be accepted, else it is considerred to be failed
      - name: Restart TTDK_API
        run: |
          echo "TTDK_API"
      - name: cURL AxiosJS
        # You may pin to the exact commit or the version.
        # uses: indiesdev/curl@5f733a4ab67799ec174b9b9b3f8d78100ae084e8
        uses: indiesdev/curl@v1.1
        with:
          # The target url
          url: ${{ secrets.TTDK_API }}
          # The request method, basically one of GET, POST, PUT, PATCH
          method: "POST" # optional, default is GET
          # List of status codes to be accepted, else it is considerred to be failed
      - name: Restart TTDK_API_CDN_TRUNGTAM
        run: |
          echo "TTDK_API_CDN_TRUNGTAM"
      - name: cURL AxiosJS
        # You may pin to the exact commit or the version.
        # uses: indiesdev/curl@5f733a4ab67799ec174b9b9b3f8d78100ae084e8
        uses: indiesdev/curl@v1.1
        with:
          # The target url
          url: ${{ secrets.TTDK_API_CDN_TRUNGTAM }}
          # The request method, basically one of GET, POST, PUT, PATCH
          method: "POST" # optional, default is GET
          # List of status codes to be accepted, else it is considerred to be failed
      - name: Restart TTDK_API_TRUNGTAM
        run: |
          echo "TTDK_API_TRUNGTAM"
      - name: cURL AxiosJS
        # You may pin to the exact commit or the version.
        # uses: indiesdev/curl@5f733a4ab67799ec174b9b9b3f8d78100ae084e8
        uses: indiesdev/curl@v1.1
        with:
          # The target url
          url: ${{ secrets.TTDK_API_TRUNGTAM }}
          # The request method, basically one of GET, POST, PUT, PATCH
          method: "POST" # optional, default is GET
          # List of status codes to be accepted, else it is considerred to be failed
      - name: Restart TTDK_API_WORKER
        run: |
          echo "TTDK_API_WORKER"
      - name: cURL AxiosJS
        # You may pin to the exact commit or the version.
        # uses: indiesdev/curl@5f733a4ab67799ec174b9b9b3f8d78100ae084e8
        uses: indiesdev/curl@v1.1
        with:
          # The target url
          url: ${{ secrets.TTDK_API_WORKER }}
          # The request method, basically one of GET, POST, PUT, PATCH
          method: "POST" # optional, default is GET
          # List of status codes to be accepted, else it is considerred to be failed
      - name: Restart TTDK_API_ZALO_AUTHEN
        run: |
          echo "TTDK_API_ZALO_AUTHEN"
      - name: cURL AxiosJS
        # You may pin to the exact commit or the version.
        # uses: indiesdev/curl@5f733a4ab67799ec174b9b9b3f8d78100ae084e8
        uses: indiesdev/curl@v1.1
        with:
          # The target url
          url: ${{ secrets.TTDK_API_ZALO_AUTHEN }}
          # The request method, basically one of GET, POST, PUT, PATCH
          method: "POST" # optional, default is GET
          # List of status codes to be accepted, else it is considerred to be failed
      - name: Telegram sender
        uses: robotomize/notify-telegram@v0.2.4
        if: always()
        with:
          chat: "@BuildNotify" # user id or channel name secret
          token: "5665305274:AAFlhbcpNijafxo9sCNqO2CBuojoRNP5ZFc" # token secret
          status: ${{ job.status }} # do not modify this line
          message: "Reset BO Services" # custom message
          
         
          
