name: Trigger build of all BO Services

on:
  workflow_call:
    inputs:
      upload-artifact:
        type: boolean
        default: true

jobs:
  reset-all-services:
    name: reset-all-services
    runs-on: "ubuntu-20.04"
    steps:
      - name: Restart BOOKEDA Service
        run: |
          echo "BOOKEDA"
      - name: cURL AxiosJS
        # You may pin to the exact commit or the version.
        # uses: indiesdev/curl@5f733a4ab67799ec174b9b9b3f8d78100ae084e8
        uses: indiesdev/curl@v1.1
        if: always()
        id: reset_BOOKEDA
        with:
          # The target url
          url: ${{ secrets.BOOKEDA }}
          # The request method, basically one of GET, POST, PUT, PATCH
          method: "POST" # optional, default is GET
          # List of status codes to be accepted, else it is considerred to be failed
          timeout: 3000
      - name: Restart BOFLOWTEAM
        run: |
          echo "BOFLOWTEAM"
      - name: cURL AxiosJS
        # You may pin to the exact commit or the version.
        # uses: indiesdev/curl@5f733a4ab67799ec174b9b9b3f8d78100ae084e8
        uses: indiesdev/curl@v1.1
        if: always()
        id: reset_BOFLOWTEAM
        with:
          # The target url
          url: ${{ secrets.BOFLOWTEAM }}
          # The request method, basically one of GET, POST, PUT, PATCH
          method: "POST" # optional, default is GET
          # List of status codes to be accepted, else it is considerred to be failed
          timeout: 3000
      - name: Restart BO_NASDAQ
        run: |
          echo "BO_NASDAQ"
      - name: cURL AxiosJS
        # You may pin to the exact commit or the version.
        # uses: indiesdev/curl@5f733a4ab67799ec174b9b9b3f8d78100ae084e8
        uses: indiesdev/curl@v1.1
        if: always()
        id: reset_BO_NASDAQ
        with:
          # The target url
          url: ${{ secrets.BO_NASDAQ }}
          # The request method, basically one of GET, POST, PUT, PATCH
          method: "POST" # optional, default is GET
          # List of status codes to be accepted, else it is considerred to be failed
          timeout: 3000
      
      - name: Restart TTDK_API
        run: |
          echo "TTDK_API"
      - name: cURL AxiosJS
        # You may pin to the exact commit or the version.
        # uses: indiesdev/curl@5f733a4ab67799ec174b9b9b3f8d78100ae084e8
        uses: indiesdev/curl@v1.1
        if: always()
        id: reset_TTDK_API
        with:
          # The target url
          url: ${{ secrets.TTDK_API }}
          # The request method, basically one of GET, POST, PUT, PATCH
          method: "POST" # optional, default is GET
          # List of status codes to be accepted, else it is considerred to be failed
          timeout: 3000
          
      - name: Restart TTDK_API_CDN_TRUNGTAM
        run: |
          echo "TTDK_API_CDN_TRUNGTAM"
      - name: cURL AxiosJS
        # You may pin to the exact commit or the version.
        # uses: indiesdev/curl@5f733a4ab67799ec174b9b9b3f8d78100ae084e8
        uses: indiesdev/curl@v1.1
        if: always()
        id: reset_TTDK_API_CDN_TRUNGTAM
        with:
          # The target url
          url: ${{ secrets.TTDK_API_CDN_TRUNGTAM }}
          # The request method, basically one of GET, POST, PUT, PATCH
          method: "POST" # optional, default is GET
          # List of status codes to be accepted, else it is considerred to be failed
          timeout: 3000
      - name: Restart TTDK_API_TRUNGTAM
        run: |
          echo "TTDK_API_TRUNGTAM"
      - name: cURL AxiosJS
        # You may pin to the exact commit or the version.
        # uses: indiesdev/curl@5f733a4ab67799ec174b9b9b3f8d78100ae084e8
        uses: indiesdev/curl@v1.1
        if: always()
        with:
          # The target url
          url: ${{ secrets.TTDK_API_TRUNGTAM }}
          # The request method, basically one of GET, POST, PUT, PATCH
          method: "POST" # optional, default is GET
          # List of status codes to be accepted, else it is considerred to be failed
          timeout: 3000
          
      - name: Restart TTDK_API_WORKER
        run: |
          echo "TTDK_API_WORKER"
      - name: cURL AxiosJS
        # You may pin to the exact commit or the version.
        # uses: indiesdev/curl@5f733a4ab67799ec174b9b9b3f8d78100ae084e8
        uses: indiesdev/curl@v1.1
        if: always()
        id: reset_TTDK_TTDK_API_WORKER
        with:
          # The target url
          url: ${{ secrets.TTDK_API_WORKER }}
          # The request method, basically one of GET, POST, PUT, PATCH
          method: "POST" # optional, default is GET
          # List of status codes to be accepted, else it is considerred to be failed
          timeout: 3000
      - name: Telegram sender
        uses: robotomize/notify-telegram@v0.2.4
        if: always()
        with:
          chat: "@BuildNotify" # user id or channel name secret
          token: "5665305274:AAFlhbcpNijafxo9sCNqO2CBuojoRNP5ZFc" # token secret
          status: ${{ job.status }} # do not modify this line
          message: |
            Services result summary:
            reset_BOOKEDA ${{steps.reset_BOOKEDA.conclusion}}
            reset_BO_NASDAQ ${{steps.reset_BO_NASDAQ.conclusion}}
            reset_TTDK_API ${{steps.reset_TTDK_API.conclusion}}
            reset_TTDK_API_CDN_TRUNGTAM ${{steps.reset_TTDK_API_CDN_TRUNGTAM.conclusion}}
            reset_TTDK_TTDK_API_WORKER ${{steps.reset_TTDK_TTDK_API_WORKER.conclusion}}
          
          
         
          
